dependencies:
  - name: provendb-proxy
    version: 0.2.0
    condition: provendb-proxy.enabled
  - name: provendb-tree
    version: 0.1.0
    condition: provendb-tree.enabled  
    import-values:
      - child: tree.host
        parent: provendb-api-gateway.tree.host  
      - child: tree.host
        parent: provendb-concierge.tree.host    
  - name: provendb-user
    version: 0.1.0
    condition: provendb-user.enabled  
    import-values:
      - child: grpc
        parent: provendb-api-gateway.grpc
      - child: domain
        parent: provendocs.user.domain  
  - name: provendb-api-gateway
    version: 0.1.0
    condition: provendb-api-gateway.enabled  
    import-values:
      - child: domain
        parent: provendocs.apigateway.domain 
      - child: host
        parent: provendocs.apigateway.host
  - name: provendb-concierge
    version: 0.1.0
    condition: provendb-concierge.enabled  
  - name: provendocs
    version: 0.1.0
    condition: provendocs.enabled