apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "baseName" . }}-provendb-proxy-configmap
  namespace: {{ .Release.Namespace }}
data:
  proxy.mongodb.ssl: {{ .Values.proxy.sslEnabled | quote }}
  
  proxy.port: {{ .Values.proxy.port | quote }}
  proxy.userDatabases: {{ .Values.proxy.userDatabases | quote }}
  proxy.ssl.enable: {{ .Values.proxy.sslEnabled | quote }}
  proxy.treeservice.host: {{ template "baseName" . }}-provendb-tree-service.{{ .Release.Namespace }}.svc.cluster.local
  proxy.treeservice.dbinstance: {{ .Values.tree.dbinstance | quote }}
  proxy.max.connections: {{ .Values.proxy.maxConnections | quote }}
  proxy.max.threads: {{ .Values.proxy.maxThreads | quote }}
  proxy.auth.enabled: {{ .Values.proxy.auth.enabled | quote }}
  proxy.mongo.auth.uri: {{ .Values.proxy.auth.uri | quote }}

  proxy.sidecarmongodb.port: {{ .Values.proxy.sidecarmongodb.port | quote }}
  proxy.sidecarmongodb.bind.ip: {{ .Values.proxy.sidecarmongodb.bindip | quote }}
  proxy.data.size.gb.limit: {{ .Values.proxy.dataSizeGBLimit | quote }}
  proxy.healthcheck.host: {{ .Values.proxy.healthcheck.host | quote }}
  proxy.chainpoint.nodes: {{ .Values.proxy.chainpoint.nodes | quote }}
  proxy.env: {{ .Values.proxy.env }}
  tree.port: {{ .Values.tree.port | quote }}
  jaeger-agent.host.port: {{ .Values.jaegeragent.host.port | quote }}
  