apiVersion: v1
kind: Secret
metadata:
  name: proxy-{{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  proxy.mongodb.uri: {{ .Values.proxy.mongodb.uri | b64enc }}
  proxy.auth.username: {{ .Values.proxy.auth.username | b64enc }}
  proxy.auth.password: {{ .Values.proxy.auth.password | b64enc }}
  proxy.p12.file.password: {{ .Values.proxy.p12.filePassword | b64enc }}