apiVersion: v1
kind: Secret
metadata:
  name: {{ template "baseName" . }}-provendb-proxy-secret
type: Opaque
data:
  proxy.auth.username: {{ .Values.proxy.auth.username  | b64enc}}
  proxy.auth.password: {{ .Values.proxy.auth.password  | b64enc}}
