apiVersion: v1
kind: Service
metadata:
  name: provendb-proxy-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-proxy-{{ .Release.Name }}
  ports:
    - name: provendb-proxy-{{ .Release.Name }}-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.proxy.port }} 
      protocol: TCP
  type: {{ .Values.service.type }}
