apiVersion: v1
kind: Service
metadata:
  name: provendb-proxy-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-proxy-{{ .Release.Name }}
  ports:
    - name: provendb-proxy-{{ .Release.Name }}-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.proxy.port }} 
      protocol: TCP
  {{ if eq .Values.parent true}}
    {{ if eq  .Release.Namespace "staging"}}
      loadBalancerIP: {{ .Values.externalIpStaging }}
    {{ else if eq  .Release.Namespace  "production"}}  
      loadBalancerIP: {{ .Values.externalIpProduction }}
    {{ end }}
  {{ else }}  
    type: {{ .Values.service.type }} 
  {{ end }}
