apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-proxy-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  proxy.mongodb.username: {{ .Values.proxy.mongodb.username | b64enc }}
  proxy.mongodb.password: {{ .Values.proxy.mongodb.password | b64enc }}