apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-service
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyImage: docker.io/istio/proxyv2:0.8.0
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: proxy-sidecar-mongodb
          image: mongo:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ .Release.Name }}-sidecar-mongodb-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongo
                - --port
                - $(SIDECAR_MONGODB_PORT)
                - --eval
                - db.stats()
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 30
          livenessProbe:
            exec:
              command:
                - mongo
                - --port
                - $(SIDECAR_MONGODB_PORT)
                - --eval
                - db.stats()
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
          command: [ "/bin/sh", "-c", "(mongod  --fork --logpath /var/log/mongod.log --port 27017 --bind_ip ${BIND_IP} ) && \
                      mongo --host $BIND_IP $USER_DATABASES --port 27017 --eval \"var userPresent = db.runCommand({ usersInfo: { user: '$AUTH_USERNAME', db: '$USER_DATABASES' } }).users.length > 0;
                      if(!userPresent){
                        db.runCommand({ createRole: 'superadmin', privileges: [], roles: [] });
                        db.runCommand({ createRole: 'superadmin', privileges: [], roles: [] });
                        db.runCommand({ createRole: 'superadmin', privileges: [], roles: [] });
                        db.runCommand({ createUser: '$AUTH_USERNAME', pwd: '$AUTH_PASSWORD', roles: [{ role: 'superadmin', db: '$USER_DATABASES' }] })
                      }\" && \
                      tail -f /var/log/mongod.log"]
          env:
            - name: SIDECAR_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.sidecarmongodb.port
            - name: USER_DATABASES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.userDatabases
            - name: BIND_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.sidecarmongodb.bind.ip
            - name: AUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.auth.username
            - name: AUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.auth.password
        - name: proxy
          image: asia.gcr.io/provendb/provendb-proxy:latest
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.proxy.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.proxy.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          ports:
            - containerPort: {{ .Values.proxy.port }}
          command: ["/bin/bash"]
          args: [
              "-c",
              "./proxy-server.sh \
              ${USER_DATABASES} \
              ${PROXY_PORT} \
              ${PROXY_MONGODB_URI} \
              ${MAX_THREADS} \
              ${MAX_CONNECTIONS} \
              ${PROXY_AUTH_ENABLED} \
              ${PROXY_MONGO_AUTH_URI}"
            ]
          env:
            - name: PROXY_MONGO_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.mongo.auth.uri
            - name: PROXY_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: proxy.mongodb.uri
            - name: PROXY_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.port
            - name: USER_DATABASES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.userDatabases
            - name: PROXY_MONGODB_SSL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.mongodb.ssl
            - name: ENV_TREE_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.treeservice.host
            - name: ENV_TREE_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.treeservice.port
            - name: ENV_TREE_SERVICE_DB_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.treeservice.dbinstance
            - name: MAX_THREADS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.max.threads
            - name: MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.max.connections
            - name: PROXY_AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: proxy.auth.enabled
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-sidecar-mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
