apiVersion: v1
kind: Service
metadata:
  name: provendb-io-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-io-{{ .Release.Name }}
  ports:
    - name: provendb-io-{{ .Release.Name }}-port
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP