apiVersion: v1
kind: Service
metadata:
  name: provendb-io-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-io
  ports:
    - name: provendb-io-port
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP