replicaCount: 1
istioSidecarInject: false

service:
  type: LoadBalancer
  port: 27017

proxy:
  image:
    repository: asia.gcr.io/provendb/provendb-proxy
    tag: latest
  mongodb:
    uri: "mongodb+srv://sbs:DBEnvy2016@mongogcp1-oexhg.gcp.mongodb.net/provendocs-helm"

  sidecarmongodb:
    port: 27017
    bindip: "127.0.0.1"

  port: 27018
  userDatabases: provendocs-helm

  sslEnabled: "true"
  maxConnections: 10
  maxThreads: 50
  auth:
    enabled: "true"
    uri: "mongodb://localhost:27017"
    username: "admin"
    password: "password"
  p12:
    filePassword: "provendb"

tree:
  host:
    port: 10000
  dbinstance: "local-dev"    

parent: false  

