replicaCount: 1

service:
  type: LoadBalancer
  port: 27018

proxy:
  mongodb:
    uri: "mongodb+srv://sbs:DBEnvy2016@provendb-staging-vki7g.gcp.mongodb.net/provendocs"

  sidecarmongodb:
    port: 27017
    bindip: "127.0.0.1"

  port: 27018
  userDatabases: provendocs

  treeservice:
    host: "treeservice-service.staging.svc.cluster.local"
    port: 10000
    dbinstance: "local-dev"

  sslEnabled: "true"
  maxConnections: 10
  maxThreads: 50
  auth:
    enabled: "true"
    uri: "mongodb://localhost:27017"
    username: "admin"
    password: "password"
  p12:
    filePassword: "provendb"

