replicaCount: 1
istioSidecarInject: true
safeToEvict: true

service:
  type: LoadBalancer
  port: 27017
  # if type is LoadBalancer, you can specify loadBalancerSourceRanges
  loadBalancerSourceRanges: []

proxy:
  image:
    repository: southbanksoftware/provendb-proxy
    tag: latest
  chainpoint:
    nodes: http://35.235.91.33
  sidecarmongodb:
    port: 27017
    bindip: "127.0.0.1"
    image:
      repository: mongo
      tag: "4.2.0"
  port: 27018
  userDatabases: provendb_stg
  healthcheck:
    host: localhost
  sslEnabled: "true"
  maxConnections: 10
  maxThreads: 50
  auth:
    enabled: "true"
    uri: "mongodb://localhost:27017"
    username: "admin"
    password: "password"
  dataSizeGBLimit: 1GB  
  env: "prd"
  jvm: "-Xms256M -Xmx768M"
  grpc:
    port: 10018
  mongodb:
    uri: "sdf"
  domainName:

replicaCount: 1 

tree:
  dbinstance: "local-dev"  
  port: 10000  

jaegeragent:
  host:
    port: jaeger-agent.istio-system.svc.cluster.local:6831

prometheus:
  port: 9091  
  enable: true    

kubecost:
  teamName: core  
  productName: proxy

anchor:
  host: provendb-anchor-service
  port:  10008