replicaCount: 1

service:
  type: LoadBalancer
  port: 27018

proxy:
  mongodb:
    uri: "mongodb+srv://sbs:DBEnvy2016@provendb-staging-vki7g.gcp.mongodb.net/provendocs"
    ssl: "false"

  sidecarmongodb:
    port: 27017

  port: 27018
  userDatabases: provendocs

  treeservice:
    host: "treeservice-service.staging.svc.cluster.local"
    port: 10000
    dbinstance: "local-dev"

  maxconnections: 10
  maxthreads: 50
  authentication: "NONE"


