apiVersion: v1
kind: ConfigMap
metadata:
  name: provendb-ui-configmap
  namespace: {{ .Release.Namespace }}
data:
  user.module.url: {{ .Values.user.domain.name }}
  provendb.url: {{ .Values.url }}
  api.url: {{ .Values.apigateway.domain.name }}
  internal.api.url: provendb-api-gateway-service.{{ .Release.Namespace }}.svc.cluster.local:{{ template "provendb-ui.apigatewayport" . }}
