apiVersion: v1
kind: Service
metadata:
  name: provendb-ui-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-ui
  ports:
    - name: provendb-ui-port
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
      protocol: TCP