apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "baseName" . }}-provendb-tree-configmap
  namespace: {{ .Release.Namespace }}
data:
  mongodbcache.bind.ip: {{ .Values.mongodbcache.bindip | quote }}
  mongodbcache.port: {{ .Values.mongodbcache.port | quote }}
  tree.cachedb.uri: "mongodb://{{ .Values.mongodbcache.bindip }}:{{ .Values.mongodbcache.port }}"
  tree.host.port: "0.0.0.0:{{ .Values.tree.host.port }}"
  tree.env: {{ .Values.tree.env }}
  tree.mongo.targetDB: {{ .Values.tree.targetDB }}
  tree.port: {{ .Values.tree.host.port  | quote }}
  jaeger-agent.host.port: {{ .Values.jaegeragent.host.port | quote }}
