apiVersion: v1
kind: Secret
metadata:
  name: provendb-tree-{{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  tree.mongo.targetDB.uri: {{ .Values.tree.targetDBuri | b64enc }}

