apiVersion: v1
kind: ConfigMap
metadata:
  name: provendocs-configmap
  namespace: {{ .Release.Namespace }}
data:
  provendocs.github.login.auth.callback: "http://{{ .Values.docs.url }}/auth/github/callback"
  provendocs.github.signup.callback: "http://{{ .Values.docs.url }}/signup/github/callback"
  #Google
  provendocs.google.auth.callback: "http://{{ .Values.docs.url }}/auth/google/callback"
  provendocs.google.signup.callback: "http://{{ .Values.docs.url }}/signup/google/callback"

  provendocs.user.module.url: {{ .Values.user.domain.name }}
  provendocs.docs.url: {{ .Values.docs.url }}
  # provendocs.uri: "mongodb://{{ .Values.proxy.auth.username}}:{{ .Values.proxy.auth.password }}@provendb-proxy-service.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.proxy.port }}/{{ template "dbfromuri" . }}"
  provendocs.uri: "mongodb://admin:password@proxy.provendb.com:27018/provendocs"
  provendocs.api.url: {{ .Values.apigateway.domain.name }}
  provendocs.internal.api.url: provendb-api-gatewayservice.{{ .Release.Namespace }}.svc.cluster.local:{{ template "apigatewayport" . }}
  provendocs.env: {{ .Values.env }}