apiVersion: v1
kind: Service
metadata:
  name: provendocs-{{ .Release.Name }}-service
  namespace: staging
spec:
  selector:
    app: provendocs-{{ .Release.Name }}
  ports:
    - name: provendocs-{{ .Release.Name }}
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
      protocol: TCP