##################################################################################################
# Provendb Ingress
##################################################################################################

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: provendb-gateway
  namespace: staging
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - hosts:
    - "proxy.provendb.io"
    port:
      number: 27017
      protocol: MONGO
      name: mongo
  - hosts:
    - "provendocs.com"
    port:
      number: 80
      protocol: http
      name: http-provendocs-port     
  - hosts:
    - "apigateway.provendb.com"
    port:
      number: 80
      protocol: http
      name: http-apigateway-port     
  - hosts:
    - "usermodule.provendb.com"
    port:
      number: 80
      protocol: http
      name: http-usermodule-port   
  - hosts:
    - "provendb.com"
    port:
      number: 80
      protocol: http
      name: http-provendb-port         
     
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provendb-proxy
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "proxy.provendb.io"
  gateways:
  - provendb-gateway
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: provendb-proxy-{{ .Release.Name }}-service
        port:
          number: 27017
          # name: proxy-port            


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provendocs
  namespace: staging
spec:
  hosts:
    - "provendocs.com"
  gateways:
  - provendb-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8888
          # name: provendocs-port
        host: provendocs-service.staging.svc.cluster.local

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provendb-ui
  namespace: staging
spec:
  hosts:
    - "provendb.com"
  gateways:
  - provendb-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8088
          # name: provendb-ui-landing-page-port
        host: provendb-ui-service

---        

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provendb-api-gateway
  namespace: staging
spec:
  hosts:
    - "apigateway.provendb.com"
  gateways:
  - provendb-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
          # name: provendocs-port
        host: provendb-api-gateway-service

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provendb-user
  namespace: staging
spec:
  hosts:
    - "usermodule.provendb.com"
  gateways:
  - provendb-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: provendb-user-service

---        

##################################################################################################
# Chainpoint Node Egress
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: chainpoint-external
spec:
  hosts:
  - 13.238.131.2
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - storage.googleapis.com
  - googleapis.com
  - registry.npmjs.org
  - registry.yarnpkg.com
  - accounts.google.com
  - provendbui.provendb.com
  - storage.cloud.google.com
  - cloud.google.com
  - 35.201.11.36
  - '*.chainpoint.org'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL 

---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: provendb-proxy
spec:
  hosts:
  - '*.proxy.provendb.io'
  ports:
  - number: 27018
    name: mongo
    protocol: mongo
  resolution: NONE
  location: MESH_EXTERNAL 

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: github
spec:
  hosts:
  - api.github.com
  - github.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  - number: 80
    name: http
    protocol: http
  resolution: DNS

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: atlas
spec:
  hosts:
  - cloud.mongodb.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  - number: 80
    name: http
    protocol: http
  resolution: DNS  

---
# The ones below need to be removed. Only for testing purposes

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: debian
spec:
  hosts:
  - dl-cdn.alpinelinux.org
  - keyserver.ubuntu.com
  - repo.mongodb.org
  - archive.ubuntu.com
  - security.ubuntu.com
  - fastdl.mongodb.org
  - cdn-fastly.deb.debian.org
  - deb.debian.org
  - security.debian.org
  - security-cdn.debian.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL   
  

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: github
spec:
  hosts:
  - github.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - github.com
    route:
    - destination:
        host: github.com
        port:
          number: 443
      weight: 100  

# ---
  
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: chainpoint
# spec:
#   hosts:
#   - '*.chainpoint.org'
#   tls:
#   - match:
#     - port: 443
#       sni_hosts:
#       - '*.chainpoint.org'
#     route:
#     - destination:
#         host: '*.chainpoint.org'
#         port:
#           number: 443
#       weight: 100    

---     
#https://github.com/istio/istio/issues/7603

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api.github
spec:
  hosts:
  - api.github.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.github.com
    route:
    - destination:
        host: api.github.com
        port:
          number: 443
      weight: 100      
