apiVersion: v1
kind: Secret
metadata:
  name: provendb
type: Opaque
data:
  anchor.eth.endpoint: {{ index .Values "provendb-anchor" "anchor" "endpoint" | b64enc}}
  anchor.eth.private-key: {{ index .Values "provendb-anchor" "anchor" "private-key" | b64enc}}
  proxy.p12.file.password: suku #Only a placeholder
  targetDBUri: {{ .Values.global.targetDBURI  | b64enc}}
  blockcypher.token: {{ .Values.global.blockcypher.token | b64enc}}