apiVersion: v1
kind: Secret
metadata:
  name: provendb
type: Opaque
data:
  anchor.eth.testnet.secretKey.endpoint: {{ index .Values "provendb-anchor" "anchor" "eth" "testnet" "endpoint" | b64enc}}
  anchor.eth.testnet.secretKey.privateKey: {{ index .Values "provendb-anchor" "anchor"  "eth" "testnet" "privatekey" | b64enc}}
  proxy.p12.file.password: suku #Only a placeholder
  targetDBUri: {{ .Values.global.targetDBURI  | b64enc}}
  blockcypher.token: {{ .Values.global.blockcypher.token | b64enc}}