# This applies to GCP
{{if eq  .Values.global.cloud "GCP"}} 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
{{else if eq .Values.global.cloud "AZURE" }}
# This applies to Azure
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
{{ else if eq .Values.global.cloud "MINIKUBE" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: k8s.io/minikube-hostpath
{{ else if eq .Values.global.cloud "DOCKER_DESKTOP_KUBERNETES" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: docker.io/hostpath
{{ else }}
{{ end }}


