
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provendb-api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: provendb-api-gateway
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: {{ .Values.istioSidecarInject | quote }} 
      labels:
        app: provendb-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        # resources:
          # requests:
          #   memory: "2Gi" # 4 GB
          #   cpu: "1000m"  # 1 CPUs
          # limits:
          #   memory: "4Gi" # 4 GB
          #   cpu: "2000" #  1 CPUs    
        livenessProbe:
          httpGet:
              path: /
              port: {{ template "port" . }}
          initialDelaySeconds: 5 #wait this period after starting fist time
          periodSeconds: 30  # polling interval
          timeoutSeconds: 60    # wish to receive response within this time period
        readinessProbe: 
          httpGet:
              path: /
              port: {{ template "port" . }}
          initialDelaySeconds: 5 #wait this period after staring fist time
          periodSeconds: 30    # polling interval
          timeoutSeconds: 60   
        ports:
        - containerPort: 8080
        command: ["./api-gateway"]
        env:
          - name: API_GATEWAY_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.host.port
          - name: API_GATEWAY_TREE_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.tree.host.port
          - name: API_GATEWAY_USER_MODULE_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.user.module.host.port
          - name: API_GATEWAY_OAUTH_REDIRECT_HOST
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.oauth.redirect.host
          - name: API_GATEWAY_USER_MODULE_DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.user.module.domain.name
          - name: API_GATEWAY_DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.domain.name      
          - name: API_GATEWAY_ALLOWED_URLS
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.allowed.urls
          - name: API_GATEWAY_CONCIERGE_HOST_PORT      
            valueFrom:
              configMapKeyRef:
                name: provendb-api-gateway-configmap
                key: apigateway.concierge.host.port