apiVersion: v1
kind: Service
metadata:
  name: provendb-api-gateway-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-api-gateway-{{ .Release.Name }}
  ports:
    - name: http-port
      port: {{ template "port" . }}
      targetPort: {{ template "port" . }}
      protocol: TCP