apiVersion: v1
kind: Service
metadata:
  name: provendocs-thumbnail-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendocs-thumbnail
  ports:
    - name: provendocs-thumbnail-port
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
      protocol: TCP