##################################################################################################
# Deployment
##################################################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-treeservice
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-treeservice-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-treeservice
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true" #Open issue https://github.com/istio/istio/issues/9571
      labels:
        app: {{ .Release.Name }}-treeservice
    spec:
      containers:
      - name: mongodb-cache
        image: mongo:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Values.treeservice.mongodbcache.pvcname }}
          mountPath: /data/db
{{ toYaml .Values.treeservice.mongodbcache.resources | indent 10 }}   
        readinessProbe: 
          exec:
            command:
            - bash
            - "-c"
            - |
              mongo --eval "db.stats()" --port ${MONGODBCACHE_PORT} --host ${MONGODBCACHE_BIND_IP}
          initialDelaySeconds: 60 #wait this period after staring fist time
          periodSeconds: 30    # polling interval every 30 seconds
          timeoutSeconds: 60 
        livenessProbe: 
          exec:
            command:
            - bash
            - "-c"
            - |
              mongo --eval "db.stats()" --port ${MONGODBCACHE_PORT} --host ${MONGODBCACHE_BIND_IP}
          initialDelaySeconds: 60 #wait this period after staring fist time
          periodSeconds: 30    # polling interval every 30 seconds
          timeoutSeconds: 60   
        command: ["/bin/bash", "-c"]
        # args: ["-c","tail -f /etc/hosts"]
        args: ["-c","mongod --port ${MONGODBCACHE_PORT} --bind_ip ${MONGODBCACHE_BIND_IP} --replSet test && \
                                    mongo --eval \"rs.initiate({_id: 'test',
                                                                members: [
                                                                    {
                                                                    _id: 0,
                                                                    host: '127.0.0.1:30010'
                                                                    },
                                                                ]
                                                                })\""] 
        env:
          - name: MONGODBCACHE_BIND_IP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.mongodbcache.bind.ip
          - name: MONGODBCACHE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.mongodbcache.port   
      - name: tree-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ include "treeservice.host.port" . }}
        volumeMounts:
        - name: {{ .Values.treeservice.mongodbcache.pvcname }}
          mountPath: /data/db
        resources: 
{{ toYaml .Values.treeservice.host.resources | indent 10 }}  
        readinessProbe:
          tcpSocket:
            port: {{ include "treeservice.host.port" . }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 60
        livenessProbe:
          tcpSocket:
            port: {{ include "treeservice.host.port" . }}
          initialDelaySeconds: 30
          periodSeconds: 120 
          timeoutSeconds: 60
        command: ["./tree"]
        env:
          - name: TREE_CACHE_DB_URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.cachedb.uri
          - name: TREE_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.host.port
          - name: mongoUri
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.mongo.targetDB.uri
          - name: TREE_ENV
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.treeenv
          - name: mongoTargetDB
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-treeservice-configmap
                key: treeservice.mongo.targetDB     

    
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.treeservice.mongodbcache.pvcname }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: "50Gi"