##################################################################################################
# Treeservice service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-treeservice-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ include "treeservice.host.port" . }}
      targetPort: {{ include "treeservice.host.port" . }}
      protocol: TCP
      name: treeservice-port
  selector:
    app: {{ .Release.Name }}-treeservice
---    