kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd