replicaCount: 2
istioSidecarInject: false

http:
  port: 8888

image:
  repository: asia.gcr.io/provendb/provendocs
  tag: latest

docs:
  url: provendocs.com    

env: prod

#optional when installing the parent chart
