replicaCount: 2
istioSidecarInject: false

http:
  port: 8888

image:
  repository: asia.gcr.io/provendb/provendocs
  tag: latest

docs:
  url: provendocs.com    

env: prod

mongo:  
  uri: "mongodb://admin:password@proxy.provendb.io/provendocs-helm"

thumb:
  uri: "provendocs-thumbnail-service:8889"

sg:
  api:
    key: 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  

#optional when installing the parent chart
