apiVersion: v1
kind: ConfigMap
metadata:
  name: provendb-user-{{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
    usermodule.mongo.uri: {{ .Values.mongo.uri | quote }}
    usermodule.grpc.host.port: "0.0.0.0:{{ .Values.grpc.port }}"
    usermodule.http.host.port: "0.0.0.0:{{ .Values.http.port }}"
    usermodule.domain.name: {{ .Values.domain.name }} #Redirect