apiVersion: v1
kind: Secret
metadata:
  name: provendb-user-{{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
   usermodule.google.oauth.clientid: {{ .Values.google.oauth.clientid | b64enc }}
   usermodule.google.oauth.secret: {{ .Values.google.oauth.secret | b64enc }}
   usermodule.github.oauth.clientid: {{ .Values.github.oauth.clientid | b64enc }}
   usermodule.github.oauth.secret: {{ .Values.github.oauth.secret | b64enc }}
