apiVersion: v1
kind: Service
metadata:
  name: provendb-user-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: provendb-user-{{ .Release.Name }}
  ports:
    - name: http-port
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
      protocol: TCP
    - name: grpc-port
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP     