replicaCount: 1
istioSidecarInject: true

image:
  repository: asia.gcr.io/provendb/provendb-api-gateway
  tag: latest

host: 
  port: 0.0.0.0:8080

tree:
  host:
    port: 10000

user:
  module:
    host:
      port: usermodule-grpc-service.staging.svc.cluster.local:1377
    domain:
      name: usermodule.provendb.com

domain:
  name: apigateway.provendb.com

allowed:
  urls: http://provendocs.com/login

concierge:
  host:
    port: concierge-service.staging.svc.cluster.local:10002         
