replicaCount: 1
istioSidecarInject: true

image:
  repository: asia.gcr.io/provendb/provendb-api-gateway
  tag: latest

host: 
  port: 0.0.0.0:8080

domain:
  name: apigateway.provendb.com

allowed:
  urls: http://provendocs.com/login       
