replicaCount: 1
istioSidecarInject: true

grpc:
  port: 1377

http:
  port: 8080

image:
  repository: asia.gcr.io/provendb/provendb-user
  tag: latest

domain:
  name: usermodule.provendb.com  

mongo:
  uri: mongodb+srv://provendb-concierge:x8dZQtma@mongogcp1-oexhg.gcp.mongodb.net

google:
  oauth:
    clientid: 489471586791-vdctntstmbrprpm302bddi38pivsa100.apps.googleusercontent.com
    secret: ofUASVCbYrCppsbcZsX-hgsH

github:
  oauth:
    clientid: 1e89e5cb42cd01b18713
    secret: ac0d6f68743558421542daecc02731b31534ade4