replicaCount: 1
istioSidecarInject: false

http:
  port: 8888

image:
  repository: asia.gcr.io/provendb/provendb-ui
  tag: latest

url: provendb.com

sg:
  api:
    key: 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
